table dim_categorie_local
	lineageTag: 020ba12b-57b1-4fff-b275-f05a547a7119

	column cle_categorie_local
		dataType: string
		lineageTag: dfc9eede-056e-4b0d-bfe6-d52b794871cd
		sourceColumn: cle_categorie_local

	column categorie_local
		dataType: string
		lineageTag: 5fb4df3f-922a-46e9-b06d-f56ad99e12ca
		sourceColumn: categorie_local

	partition dim_categorie_local = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:/Users/Lenovo/Desktop/PowerBi/Projet_Solaris/datamart/dim_categorie_local.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"cle_categorie_local", type text}, {"categorie_local", type text}}, "fr-FR")
				in
				    Typed

